import { useState, useRef, useEffect } from 'react';
import { 
  Download, Filter, Printer, TrendingUp, TrendingDown, 
  Activity, RefreshCw, FileText, BarChart3, AlertCircle, Calendar 
} from 'lucide-react';
import { openPrintPreview } from '../../services/reportExporter';
import { useReportExport } from './hooks/useReportExport';
import { ReportDefinition } from './reportConfig';
import { motion, AnimatePresence } from 'motion/react';
import { useAuth } from '../../context/AuthContext';
import { useReportAdvisory } from './hooks/useReportAdvisory';

interface ViewerProps {
  report: ReportDefinition;
  data: any[];
  cards: any[];
  recommendations: string[];
  summary: string[];
  loading: boolean;
  error: any;
  onRefresh: () => void;
  filters: any;
  onFilterChange: (filters: any) => void;
}

export default function ReportViewer({ 
  report, 
  data = [], 
  cards = [], 
  summary = [], 
  loading, 
  onRefresh,
  filters, 
  onFilterChange 
}: ViewerProps) {
  const { profile } = useAuth();
  const [isFilterOpen, setIsFilterOpen] = useState(false);
  const [viewMode, setViewMode] = useState<'standard' | 'focus'>('standard');
  const [selectedRow, setSelectedRow] = useState<any>(null);
  
  // Local UI sync
  const [searchQuery, setSearchQuery] = useState(filters?.searchQuery || '');
  
  // Update local search if filters change from outside (voice, etc.)
  useEffect(() => {
    if (filters?.searchQuery !== undefined && filters.searchQuery !== searchQuery) {
      setSearchQuery(filters.searchQuery);
    }
  }, [filters?.searchQuery]);

  const { handleExport, exporting } = useReportExport();
  
  // Intelligence Logic
  const { advisory } = useReportAdvisory(
    report?.title || 'Report', 
    (cards || []).map(c => ({ label: c?.label, value: c?.value })), 
    (data || []).slice(0, 20), 
    filters?.dateRange || 'period', 
    profile?.business_id || ''
  );
  const filteredData = (data || []).filter(row => {
    if (!row) return false;
    const matchesSearch = Object.values(row).some(val => 
      String(val || '').toLowerCase().includes(searchQuery.toLowerCase())
    );
    if (!matchesSearch) return false;

    if (filters?.paymentMode && filters.paymentMode !== 'all' && report?.filters?.includes('payment')) {
      const mode = row.payment_mode || row['Payment Mode'];
      if (String(mode || '').toLowerCase() !== filters.paymentMode.toLowerCase()) return false;
    }

    if (filters?.category && filters.category !== 'all' && report?.filters?.includes('category')) {
      const cat = row.category || row['Category'];
      if (String(cat || '').toLowerCase() !== filters.category.toLowerCase()) return false;
    }

    if (filters?.gstSlab && filters.gstSlab !== 'all' && report?.filters?.includes('gst_slab')) {
      const slab = row.gst_slab || row['GST Slab'];
      if (String(slab || '').toLowerCase() !== filters.gstSlab.toLowerCase()) return false;
    }

    if (filters?.segment && filters.segment !== 'all' && report?.filters?.includes('segment')) {
      const seg = row.segment || row['Segment'];
      if (String(seg || '').toLowerCase() !== filters.segment.toLowerCase()) return false;
    }

    if (filters?.minValue !== '' && report?.filters?.includes('threshold')) {
      const amount = row.total_amount || row.amount || row['Amount'] || row['Revenue'] || 0;
      if (Number(amount) < Number(filters.minValue)) return false;
    }

    return true;
  });

  const generateReportPayload = (): any => ({
    type: (report?.category?.toLowerCase() || 'sales') as any,
    title: report?.title || 'Report',
    category: report?.category || 'Analytics',
    description: report?.description || '',
    dateRange: filters?.dateRange === 'custom' 
      ? { from: filters?.startDate, to: filters?.endDate }
      : { from: String(filters?.dateRange), to: String(filters?.dateRange) },
    generatedBy: profile?.full_name || 'ADMIN',
    businessName: profile?.business_name || 'Vyapari Retail',
    gstin: profile?.gstin || '',
    columns: (report?.columns || []).map(c => ({
      key: c?.toLowerCase().replace(/\s+/g, '_'),
      label: c,
      type: 'text'
    })),
    rows: filteredData || [],
    advisory: (advisory || []).length ? advisory : [summary?.[0] || 'Official transaction audit report generated by Vyapari Intelligence Systems.'],
    kpis: (cards || []).map(c => ({ label: c?.label, value: c?.value })),
    filtersApplied: filters?.searchQuery || 'None'
  });

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] gap-4">
        <Activity className="animate-spin text-slate-300" size={40} />
        <div className="text-[10px] font-black text-slate-400 uppercase tracking-widest animate-pulse italic">Synchronizing Global Intelligence...</div>
      </div>
    );
  }

  return (
    <div className="bg-white min-h-screen">
      <div className="max-w-[760px] mx-auto p-[28px_32px_48px]">
        {/* Header Audit Trail */}
        <div className="flex justify-between items-center mb-[10px]">
           <div className="flex items-center gap-2">
              <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
              <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Live_Sync_Active</span>
           </div>
           <div className="text-[11px] text-slate-400 uppercase font-semibold tracking-wider">
             {profile?.business_name || 'Vyapari Retail'} · Intel_Terminal
           </div>
        </div>

        {/* Tactical Report Header */}
        <div className="bg-[#1e2a5e] rounded-[3px] p-[24px_28px_26px] mb-[12px] shadow-2xl relative overflow-hidden group">
          <div className="relative z-10">
            <div className="flex items-center gap-3 mb-[8px]">
               <FileText size={14} className="text-white/40" />
               <div className="text-[10.5px] font-bold tracking-[1px] text-white/65 uppercase">
                 {report?.category || 'Business Analytics'} · {report?.title}
               </div>
            </div>
            <div className="text-[32px] font-black text-white mb-[8px] leading-[1] italic tracking-tighter uppercase">
              {report?.title}
            </div>
            <div className="text-[13px] text-white/72 leading-[1.6] max-w-[500px]">
              {report?.description}
            </div>
          </div>
          
          {/* Executive Actions */}
          <div className="absolute top-6 right-6 flex gap-2 z-20">
             <button 
                disabled={exporting}
                onClick={() => handleExport({
                  format: 'pdf_detailed',
                  reportTitle: report?.title || 'Report',
                  period: String(filters?.dateRange),
                  businessId: profile?.business_id || '',
                  businessName: profile?.business_name || 'Vyapari Retail',
                  gstin: profile?.gstin || '',
                  kpis: (cards || []).map(c => ({ label: c?.label, value: c?.value })),
                  tableData: filteredData || [],
                  columns: report?.columns || [],
                  filtersApplied: filters?.searchQuery || 'None',
                  category: report?.category,
                  description: report?.description
                })} 
                className="p-2.5 bg-white/10 hover:bg-white/25 rounded border border-white/10 text-white transition-all backdrop-blur-xl flex items-center gap-2.5 px-4 group/btn shadow-xl"
             >
               <Download size={15} className={`${exporting ? 'animate-bounce' : 'group-hover/btn:scale-110'} transition-transform`} />
               <span className="text-[10px] font-black uppercase tracking-[0.2em]">Save_PDF</span>
             </button>
             <button 
                onClick={() => openPrintPreview(document.body, generateReportPayload())} 
                className="p-2.5 bg-white/10 hover:bg-white/25 rounded border border-white/10 text-white transition-all backdrop-blur-xl flex items-center gap-2.5 px-4 group/btn shadow-xl"
             >
               <Printer size={15} className="group-hover/btn:scale-110 transition-transform" />
               <span className="text-[10px] font-black uppercase tracking-[0.2em]">Print</span>
             </button>
          </div>
        </div>

        {/* Metadata Registry Table */}
        <table className="w-full border-collapse border border-[#d1d5db] mb-[16px]">
          <thead>
            <tr className="bg-[#f5f6f8]">
              {["Filing_Period","Registry_Node","Operator","Timestamp"].map(h => (
                <th key={h} className="text-[10px] font-black tracking-[1px] text-slate-400 uppercase p-[10px_14px] border border-[#d1d5db] text-left">{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            <tr>
              <td className="text-[13px] text-[#1a1a2e] p-[10px_14px] border border-[#d1d5db] uppercase font-black">{String(filters?.dateRange || 'period').replace('-', ' ')}</td>
              <td className="text-[13px] text-[#1a1a2e] p-[10px_14px] border border-[#d1d5db] font-black">MAIN_HUB_01</td>
              <td className="text-[13px] text-[#1a1a2e] p-[10px_14px] border border-[#d1d5db] font-black">{profile?.full_name || 'ADMIN'}</td>
              <td className="text-[13px] text-[#1a1a2e] p-[10px_14px] border border-[#d1d5db] font-black">{new Date().toLocaleTimeString()}</td>
            </tr>
          </tbody>
        </table>        {/* Primary Command Bar */}
        <div className="flex items-center justify-between mb-8 bg-[#f8fafc] p-4 rounded-xl border border-slate-200 shadow-sm">
           <div className="flex items-center gap-6">
              {/* Universal Date Trigger */}
              <div className="flex items-center gap-3">
                 <div className="p-2 bg-[#1e2a5e] text-white rounded-lg">
                    <Calendar size={18} />
                 </div>
                 <div className="flex flex-col">
                    <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest">Active_Window</span>
                    <select 
                      value={filters?.dateRange}
                      onChange={(e) => onFilterChange({ ...filters, dateRange: e.target.value })}
                      className="bg-transparent text-[13px] font-black text-[#1e2a5e] uppercase outline-none cursor-pointer p-0 m-0 border-none appearance-none"
                    >
                      <option value="today">Today</option>
                      <option value="yesterday">Yesterday</option>
                      <option value="this-month">This Month</option>
                      <option value="last-month">Last Month</option>
                      <option value="quarter">This Quarter</option>
                      <option value="custom">Custom Range</option>
                    </select>
                 </div>
              </div>

              <div className="h-8 w-px bg-slate-200" />

              <button 
               onClick={() => setIsFilterOpen(!isFilterOpen)}
               className="text-[11px] font-black uppercase tracking-[0.2em] text-[#1e2a5e] flex items-center gap-3 group"
              >
                <Filter size={16} className={`${isFilterOpen ? 'rotate-180' : ''} transition-transform`} /> 
                <span className="group-hover:underline">{isFilterOpen ? 'Hide_Advanced_Filters' : 'More_Filters'}</span>
              </button>
           </div>

           <div className="flex items-center gap-4">
              <button 
               onClick={onRefresh}
               className="p-2.5 text-slate-400 hover:text-[#1e2a5e] transition-colors bg-white border border-slate-200 rounded-lg shadow-sm"
               title="Refresh Stream"
              >
                <RefreshCw size={16} />
              </button>
              <button 
               onClick={() => setViewMode(viewMode === 'standard' ? 'focus' : 'standard')} 
               className="text-[10px] font-black uppercase tracking-[0.2em] text-[#1e2a5e] transition-all bg-white px-5 py-2.5 rounded-lg border border-slate-200 shadow-sm hover:shadow-md"
              >
                {viewMode === 'standard' ? 'Focus_Mode' : 'Exit_Focus'}
              </button>
           </div>
        </div>

        <AnimatePresence>
          {filters?.dateRange === 'custom' && (
            <motion.div 
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: 'auto', opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              className="overflow-hidden mb-6 bg-slate-50 p-6 rounded-xl border border-slate-200 border-l-4 border-l-[#1e2a5e]"
            >
              <div className="flex items-center gap-8">
                <div className="flex-1">
                  <div className="text-[10px] font-black uppercase text-slate-400 mb-2 tracking-[0.2em]">Start_Date_Selection</div>
                  <input 
                    type="date" 
                    value={filters?.startDate}
                    onChange={(e) => onFilterChange({ ...filters, startDate: e.target.value })}
                    className="w-full bg-white border border-slate-200 p-3 text-xs font-bold rounded-lg outline-none focus:border-[#1e2a5e] shadow-inner"
                  />
                </div>
                <div className="pt-6">
                   <div className="w-8 h-0.5 bg-slate-200 rounded-full" />
                </div>
                <div className="flex-1">
                  <div className="text-[10px] font-black uppercase text-slate-400 mb-2 tracking-[0.2em]">End_Date_Selection</div>
                  <input 
                    type="date" 
                    value={filters?.endDate}
                    onChange={(e) => onFilterChange({ ...filters, endDate: e.target.value })}
                    className="w-full bg-white border border-slate-200 p-3 text-xs font-bold rounded-lg outline-none focus:border-[#1e2a5e] shadow-inner"
                  />
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        <AnimatePresence>
          {isFilterOpen && (
            <motion.div 
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: 'auto', opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              className="overflow-hidden mb-8"
            >
              <div className="bg-[#f5f6f8] border-2 border-dashed border-[#d1d5db] p-8 rounded-xl grid grid-cols-1 md:grid-cols-3 gap-8">
                <div>
                   <div className="text-[10px] font-black uppercase text-slate-400 mb-3 tracking-[0.2em]">Universal_Search</div>
                   <input 
                    type="text" 
                    value={searchQuery}
                    onChange={(e) => {
                      setSearchQuery(e.target.value);
                      onFilterChange({ ...filters, searchQuery: e.target.value });
                    }}
                    placeholder="Keywords..."
                    className="w-full bg-white border border-[#d1d5db] p-3 text-xs font-bold rounded-lg outline-none focus:border-[#1e2a5e] shadow-sm"
                   />
                </div>

                {report?.filters?.includes('payment') && (
                  <div>
                    <div className="text-[10px] font-black uppercase text-slate-400 mb-3 tracking-[0.2em]">Payment_Mode</div>
                    <select 
                     value={filters?.paymentMode}
                     onChange={(e) => onFilterChange({ ...filters, paymentMode: e.target.value })}
                     className="w-full bg-white border border-[#d1d5db] p-3 text-xs font-bold rounded-lg outline-none"
                    >
                      <option value="all">All Modes</option>
                      <option value="cash">Cash</option>
                      <option value="upi">UPI</option>
                      <option value="card">Card</option>
                      <option value="credit">Credit</option>
                    </select>
                  </div>
                )}

                {report?.filters?.includes('category') && (
                  <div>
                    <div className="text-[10px] font-black uppercase text-slate-400 mb-3 tracking-[0.2em]">Stock_Category</div>
                    <select 
                     value={filters?.category}
                     onChange={(e) => onFilterChange({ ...filters, category: e.target.value })}
                     className="w-full bg-white border border-[#d1d5db] p-3 text-xs font-bold rounded-lg outline-none"
                    >
                      <option value="all">All Categories</option>
                      {Array.from(new Set((data || []).map(r => r?.category || r?.['Category']).filter(Boolean))).map(cat => (
                        <option key={String(cat)} value={String(cat).toLowerCase()}>{String(cat)}</option>
                      ))}
                    </select>
                  </div>
                )}

                {report?.filters?.includes('gst_slab') && (
                  <div>
                    <div className="text-[10px] font-black uppercase text-slate-400 mb-3 tracking-[0.2em]">GST_Slab</div>
                    <select 
                     value={filters?.gstSlab}
                     onChange={(e) => onFilterChange({ ...filters, gstSlab: e.target.value })}
                     className="w-full bg-white border border-[#d1d5db] p-3 text-xs font-bold rounded-lg outline-none"
                    >
                      <option value="all">All Slabs</option>
                      <option value="0%">0% (Tax Free)</option>
                      <option value="5%">5% (Standard)</option>
                      <option value="12%">12% (Merit)</option>
                      <option value="18%">18% (Service)</option>
                      <option value="28%">28% (Luxury)</option>
                    </select>
                  </div>
                )}

                {report?.filters?.includes('segment') && (
                  <div>
                    <div className="text-[10px] font-black uppercase text-slate-400 mb-3 tracking-[0.2em]">Customer_Segment</div>
                    <select 
                     value={filters?.segment}
                     onChange={(e) => onFilterChange({ ...filters, segment: e.target.value })}
                     className="w-full bg-white border border-[#d1d5db] p-3 text-xs font-bold rounded-lg outline-none"
                    >
                      <option value="all">All Segments</option>
                      <option value="champions">Champions</option>
                      <option value="loyal">Loyal Customers</option>
                      <option value="at-risk">At Risk</option>
                      <option value="lost">Hibernating</option>
                    </select>
                  </div>
                )}

                {report?.filters?.includes('threshold') && (
                  <div>
                    <div className="text-[10px] font-black uppercase text-slate-400 mb-3 tracking-[0.2em]">Value_Threshold</div>
                    <input 
                      type="number" 
                      value={filters?.minValue}
                      onChange={(e) => onFilterChange({ ...filters, minValue: e.target.value ? Number(e.target.value) : '' })}
                      placeholder="Min Amount..."
                      className="w-full bg-white border border-[#d1d5db] p-3 text-xs font-bold rounded-lg outline-none"
                    />
                  </div>
                )}
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Intelligence Highlights */}
        <div className="text-[12px] font-black tracking-[2px] text-slate-400 uppercase mb-[16px] flex items-center gap-3">
           <BarChart3 size={14} /> KPI_Matrix
        </div>
        
        <div className={`grid grid-cols-1 md:grid-cols-4 border border-[#d1d5db] rounded-[3px] mb-[32px] overflow-hidden transition-all duration-700 ${viewMode === 'focus' ? 'opacity-20 blur-md scale-95 pointer-events-none' : 'shadow-xl'}`}>
          {(cards || []).map((h, i) => (
            <div className="p-[20px_22px] border-r border-[#d1d5db] bg-white last:border-r-0 group/kpi hover:bg-slate-50 transition-all" key={i}>
              <div className="text-[10px] font-bold tracking-[1.5px] text-slate-500 uppercase mb-[8px] flex items-center gap-2">
                 {h?.negative ? <TrendingDown size={10} className="text-rose-500" /> : <TrendingUp size={10} className="text-emerald-500" />}
                 {h?.label}
              </div>
              <div className="text-[26px] font-black text-[#1e2a5e] leading-[1] italic tracking-tighter group-hover/kpi:translate-x-1 transition-transform">{h?.value}</div>
              {h?.trend && (
                <div className={`text-[10px] mt-[6px] font-black uppercase tracking-widest ${h?.negative ? 'text-rose-500' : 'text-emerald-600'}`}>
                   {h?.trend}
                </div>
              )}
            </div>
          ))}
        </div>

        {/* Core Data Registry */}
        <div className="text-[12px] font-black tracking-[2px] text-slate-400 uppercase mb-[16px] flex items-center gap-3">
           <RefreshCw size={14} /> Data_Registry_Feed
        </div>
        
        <div className="overflow-x-auto mb-[8px] border border-[#d1d5db] rounded-[3px] shadow-2xl">
          <table className="w-full border-collapse text-[13px]">
            <thead>
              <tr className="bg-[#1e2a5e]">
                {(report?.columns || []).map((c: string) => (
                  <th key={c} className="text-white font-black text-[11px] p-[14px_16px] text-left border-none uppercase tracking-widest whitespace-nowrap">{c}</th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-[#d1d5db]">
              {(filteredData || []).map((row, i) => (
                <tr 
                  key={i} 
                  onClick={() => setSelectedRow(row)}
                  className="hover:bg-[#f0f2f8] transition-colors cursor-pointer group"
                >
                  {(report?.columns || []).map((col: string, j: number) => (
                    <td key={j} className="p-[12px_16px] text-[#374151] border-r border-[#d1d5db] last:border-r-0 group-hover:text-[#1e2a5e] font-bold">
                      {String(Object.values(row || {})[j] ?? '—')}
                    </td>
                  ))}
                </tr>
              ))}
              {(filteredData || []).length === 0 && (
                <tr>
                  <td colSpan={(report?.columns || []).length} className="p-16 text-center text-slate-400 italic font-bold">No telemetry records found for current parameters.</td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
        <p className="text-[11px] text-slate-400 italic mb-[32px] mt-[8px] flex items-center gap-2">
          <AlertCircle size={10} /> Certified system output: This registry reflects live transaction integrity from the primary database cluster.
        </p>

        {/* Strategic Summary */}
        <div className="border-2 border-[#d1d5db] border-l-8 border-l-[#1e2a5e] rounded-xl bg-[#f0f2f8] p-[24px_28px] mb-[48px] shadow-xl">
          <div className="flex items-center gap-3 mb-[12px]">
             <Activity size={16} className="text-[#1e2a5e]" />
             <div className="text-[11px] font-black tracking-[2px] text-[#1e2a5e] uppercase">Strategic_Intelligence_Analysis</div>
          </div>
          <div className="text-[14.5px] font-medium text-[#374151] leading-[1.8] italic">
            <span className="font-black text-[#1e2a5e] not-italic block mb-2 text-[16px]">
              {(advisory?.[0] || summary?.[0] || "Strategic analysis complete.").split('.')[0]}.
            </span>
            {(advisory?.[0] || summary?.[0] || "Advanced analytical metrics suggest consistent business velocity.").split('.').slice(1).join('.')}
          </div>
        </div>

        {/* Validation Authorities */}
        <div className="border-t-2 border-[#d1d5db] pt-[32px] mt-24">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-12">
            {["Operational_Lead","Financial_Audit","Executive_Approval"].map(s => (
              <div className="pr-[16px]" key={s}>
                <div className="text-[11px] font-black text-[#1a1a2e] mb-[40px] uppercase tracking-widest border-b border-slate-100 pb-2">{s}</div>
                <div className="border-t border-dashed border-[#d1d5db] pt-[10px] text-[10px] font-black text-slate-300 uppercase tracking-widest italic">Authorization_Signature</div>
              </div>
            ))}
          </div>
        </div>

        <div className="text-center pt-16 opacity-20">
           <div className="text-[9px] font-black uppercase tracking-[0.5em]">Vyapari Intelligence Core · Terminal_V4_SECURE</div>
        </div>
      </div>

      {/* Intelligent Drill-Down Drawer */}
      <AnimatePresence>
        {selectedRow && (
          <>
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setSelectedRow(null)}
              className="fixed inset-0 bg-slate-900/60 backdrop-blur-[4px] z-[1000]"
            />
            <motion.div 
              initial={{ x: '100%' }}
              animate={{ x: 0 }}
              exit={{ x: '100%' }}
              transition={{ type: 'spring', damping: 30, stiffness: 300 }}
              className="fixed top-0 right-0 h-full w-full max-w-md bg-white shadow-[-40px_0_100px_rgba(0,0,0,0.2)] z-[1001] p-12 flex flex-col border-l border-slate-200"
            >
              <div className="flex justify-between items-start mb-12">
                <div>
                  <div className="text-[10px] font-black uppercase text-indigo-500 tracking-[0.5em] mb-3">Record_Audit_Vault</div>
                  <h3 className="text-3xl font-black text-slate-900 uppercase italic tracking-tighter leading-none">Deep_Link_Insight</h3>
                </div>
                <button 
                  onClick={() => setSelectedRow(null)}
                  className="p-4 bg-slate-50 hover:bg-slate-100 rounded-2xl transition-all border border-slate-200"
                >
                  <RefreshCw size={20} className="rotate-45" />
                </button>
              </div>

              <div className="flex-1 overflow-y-auto space-y-10 pr-4 custom-scrollbar">
                <div className="bg-[#1e2a5e] p-8 rounded-2xl shadow-2xl relative overflow-hidden">
                   <div className="absolute top-0 right-0 w-32 h-32 bg-white/5 rounded-full -translate-x-1/2 -translate-y-1/2 blur-2xl" />
                   <div className="relative z-10">
                     <div className="text-[10px] font-black uppercase text-white/50 mb-4 tracking-widest flex items-center gap-2">
                        <Activity size={12} /> Neural Summary
                     </div>
                     <p className="text-sm font-bold text-white leading-relaxed italic">
                       "This record exhibits high integrity. Contribution to total period volume is calculated at {((Number(Object.values(selectedRow || {})[2]) || 0) / (Number(String(cards?.[0]?.value || '0').replace(/[^0-9.-]+/g,"")) || 1) * 100).toFixed(1)}%. No structural anomalies detected."
                     </p>
                   </div>
                </div>

                <div className="space-y-6">
                  <div className="text-[11px] font-black uppercase text-slate-400 tracking-[0.3em] border-b border-slate-100 pb-2">Technical_Attributes</div>
                  <div className="grid grid-cols-1 gap-4">
                    {Object.entries(selectedRow || {}).map(([key, val]) => (
                      <div key={key} className="flex justify-between items-center p-5 bg-slate-50 rounded-xl border border-slate-100 group/attr">
                        <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest group-hover/attr:text-[#1e2a5e] transition-colors">{key.replace(/_/g, ' ')}</span>
                        <span className="text-[12px] font-black text-slate-900 italic">{String(val || '—')}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              <div className="pt-12 border-t border-slate-100 mt-auto">
                 <button 
                  onClick={() => handleExport({
                    format: 'pdf_single_record',
                    reportTitle: `Audit: ${report?.title || 'Report'}`,
                    period: String(filters?.dateRange),
                    businessId: profile?.business_id || '',
                    businessName: profile?.business_name || 'Vyapari Retail',
                    gstin: profile?.gstin || '',
                    kpis: [],
                    tableData: [selectedRow],
                    columns: report?.columns || [],
                    filtersApplied: filters?.searchQuery || 'None'
                  })}
                  className="w-full py-5 bg-[#1e2a5e] text-white rounded-2xl font-black text-[11px] uppercase tracking-[0.3em] hover:bg-slate-800 transition-all shadow-2xl shadow-indigo-900/20 flex items-center justify-center gap-4 italic"
                 >
                    <Download size={16} /> Export_Filing_Voucher
                 </button>
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </div>
  );
}
