import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { BankerMetrics } from "./bankerService";
import { downloadPDF } from "../utils/pdf/downloadPDF";


export const exportService = {
  generateCMAReport: async (businessName: string, metrics: BankerMetrics) => {
    const doc = new jsPDF();
    const timestamp = new Date().toLocaleString();

    // 1. Header
    doc.setFillColor(15, 23, 42); // Deep Slate
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setTextColor(159, 239, 0); // Neon Lime
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text("VYAPARI STRATEGIC AUDIT", 15, 20);
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);
    doc.text("INVESTOR-GRADE FINANCIAL SOLVENCY REPORT", 15, 30);
    doc.text(`DATE: ${timestamp}`, 150, 30);

    // 2. Business Info
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.text(`Entity: ${businessName.toUpperCase()}`, 15, 55);
    doc.setFontSize(10);
    doc.text("Sector: Retail / General Trade", 15, 62);
    
    // 3. Financial Ratios Table
    autoTable(doc, {
      startY: 70,
      head: [['Metric', 'Value', 'Benchmark', 'Status']],
      body: [
        ['Current Ratio', metrics.currentRatio.toFixed(2), '> 1.50', metrics.currentRatio > 1.5 ? 'EXCELLENT' : 'MONITOR'],
        ['Quick Ratio', metrics.quickRatio.toFixed(2), '> 1.00', metrics.quickRatio > 1.0 ? 'OPTIMAL' : 'LOW'],
        ['Debt-to-Equity', metrics.debtToEquity.toFixed(2), '< 0.50', metrics.debtToEquity < 0.5 ? 'HEALTHY' : 'HIGH'],
        ['Cash Runway', `${metrics.cashRunway.months.toFixed(1)} Months`, '> 6 Months', metrics.cashRunway.months > 6 ? 'STABLE' : 'WATCH'],
      ],
      headStyles: { fillColor: [15, 23, 42] },
      theme: 'grid'
    });

    // 4. Loan Eligibility Section
    const finalY = (doc as any).lastAutoTable.finalY || 120;
    doc.setFontSize(14);
    doc.text("CREDIT READINESS ASSESSMENT", 15, finalY + 20);
    
    doc.setFontSize(10);
    doc.rect(15, finalY + 25, 180, 25);
    doc.text(`Eligibility Score: ${metrics.loanEligibility.score}/100`, 20, finalY + 35);
    doc.text(`Status: ${metrics.loanEligibility.qualified ? 'QUALIFIED FOR WORKING CAPITAL LOAN' : 'IMPROVEMENT REQUIRED'}`, 20, finalY + 42);
    
    doc.setFont("helvetica", "italic");
    doc.text(`Analysis: ${metrics.loanEligibility.reason}`, 20, finalY + 60, { maxWidth: 170 });
    doc.setFont("helvetica", "normal");

    // 5. Receivables Risks
    autoTable(doc, {
      startY: finalY + 70,
      head: [['Top Receivables Risks', 'Exposure Amount', 'Collection Prob.']],
      body: metrics.receivablesRisks.map(r => [
        r.party,
        `INR ${r.amount.toLocaleString()}`,
        `${r.probability}%`
      ]),
      headStyles: { fillColor: [15, 23, 42] }
    });

    // 6. Growth & Trends
    const finalY2 = (doc as any).lastAutoTable.finalY || 200;
    doc.setFontSize(14);
    doc.text("GROWTH & MOMENTUM", 15, finalY2 + 20);
    
    doc.setFontSize(10);
    doc.text(`Month-over-Month (MoM): +${metrics.revenueGrowth.mom}%`, 15, finalY2 + 30);
    doc.text(`Quarter-over-Quarter (QoQ): +${metrics.revenueGrowth.qoq}%`, 15, finalY2 + 37);

    // 7. Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("This report is generated by Vyapari AI and is intended for banking and credit evaluation purposes only.", 15, 285);

    const safeBizName = businessName.replace(/[^a-zA-Z0-9-]/g, '_');
    const filename = `Vyapari_CMA_Report_${safeBizName}.pdf`;
    
    downloadPDF(doc, filename);
  },

  generateFinancialPassport: async (businessName: string, metrics: BankerMetrics) => {
    const doc = new jsPDF();
    const timestamp = new Date().toLocaleDateString();

    // 1. Passport Cover Style Header
    doc.setFillColor(10, 20, 40); // Midnight Blue
    doc.rect(0, 0, 210, 297, 'F');
    
    // Border
    doc.setDrawColor(159, 239, 0); // Neon Lime
    doc.setLineWidth(2);
    doc.rect(10, 10, 190, 277, 'S');

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(28);
    doc.text("FINANCIAL PASSPORT", 105, 50, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setTextColor(159, 239, 0);
    doc.text("OFFICIAL INSTITUTIONAL GRADE AUDIT", 105, 60, { align: 'center' });

    // Business Name
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.text(businessName.toUpperCase(), 105, 100, { align: 'center' });

    // 2. Score Badge
    doc.setFillColor(159, 239, 0, 0.1);
    doc.roundedRect(65, 120, 80, 40, 5, 5, 'F');
    doc.setFontSize(36);
    doc.setTextColor(159, 239, 0);
    doc.text(metrics.loanEligibility.score.toString(), 105, 145, { align: 'center' });
    doc.setFontSize(8);
    doc.text("NEURAL_CREDIT_SCORE", 105, 155, { align: 'center' });

    // 3. Metrics Table (Transparent/Dark Style)
    autoTable(doc, {
      startY: 180,
      head: [['KEY PERFORMANCE INDICATOR', 'VALUE', 'AI ANALYSIS']],
      body: [
        ['Current Liquidity', metrics.currentRatio.toFixed(2) + 'x', metrics.currentRatio > 1.5 ? 'EXCEPTIONAL' : 'STABLE'],
        ['Debt Capacity', (metrics.debtToEquity * 100).toFixed(1) + '%', metrics.debtToEquity < 0.5 ? 'LOW_RISK' : 'LEVERAGED'],
        ['Cash Runway', metrics.cashRunway.months.toFixed(1) + ' Months', 'CAPITAL_READY'],
        ['Revenue Momentum', `+${metrics.revenueGrowth.qoq}%`, 'ACCELERATING'],
      ],
      styles: { fillColor: [15, 23, 42], textColor: [255, 255, 255], fontSize: 9, cellPadding: 5 },
      headStyles: { fillColor: [159, 239, 0], textColor: [0, 0, 0], fontStyle: 'bold' },
      theme: 'grid',
      margin: { left: 20, right: 20 }
    });

    // 4. Recommendation Seal
    const finalY = (doc as any).lastAutoTable.finalY || 240;
    
    // Neural Audit Seal
    doc.setDrawColor(159, 239, 0);
    doc.setLineWidth(0.5);
    doc.circle(105, finalY + 45, 20, 'S');
    doc.setFontSize(6);
    doc.text("NEURAL AUDIT", 105, finalY + 40, { align: 'center' });
    doc.setFontSize(10);
    doc.text("VERIFIED", 105, finalY + 48, { align: 'center' });

    doc.setFontSize(12);
    doc.setTextColor(159, 239, 0);
    doc.text("INSTITUTIONAL GRADE CERTIFIED", 105, finalY + 75, { align: 'center' });
    doc.setFontSize(8);
    doc.setTextColor(200, 200, 200);
    doc.text("This document certifies that the business entity has passed institutional-grade solvency benchmarks.", 105, finalY + 82, { align: 'center', maxWidth: 150 });

    const safeBizName = businessName.replace(/[^a-zA-Z0-9-]/g, '_');
    const filename = `Financial_Passport_${safeBizName}.pdf`;
    
    downloadPDF(doc, filename);
  },

  generateInvoicePDF: async (business: any, invoice: any, items: any[]) => {
    try {
      const doc = new jsPDF();
      const safeStr = (val: any) => {
        if (!val) return "-";
        const s = String(val).trim();
        return s === "" ? "-" : s;
      };
      
      const businessName = safeStr(business?.name || "Universal Tech Solutions");
      let currentY = 15;

      // Expert Helper: Number to Words (Indian Style)
      const numberToWords = (num: number) => {
        const val = Math.floor(num || 0);
        if (val === 0) return "Zero Only";
        const a = ['', 'One ', 'Two ', 'Three ', 'Four ', 'Five ', 'Six ', 'Seven ', 'Eight ', 'Nine ', 'Ten ', 'Eleven ', 'Twelve ', 'Thirteen ', 'Fourteen ', 'Fifteen ', 'Sixteen ', 'Seventeen ', 'Eighteen ', 'Nineteen '];
        const b = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];
        const format = (n: number) => {
          if (n < 20) return a[n];
          if (n < 100) return b[Math.floor(n / 10)] + (n % 10 !== 0 ? ' ' + a[n % 10] : '');
          if (n < 1000) return a[Math.floor(n / 100)] + 'Hundred ' + (n % 100 !== 0 ? format(n % 100) : '');
          return '';
        };
        let words = '';
        let n = val;
        if (Math.floor(n / 10000000) > 0) { words += format(Math.floor(n / 10000000)) + 'Crore '; n %= 10000000; }
        if (Math.floor(n / 100000) > 0) { words += format(Math.floor(n / 100000)) + 'Lakh '; n %= 100000; }
        if (Math.floor(n / 1000) > 0) { words += format(Math.floor(n / 1000)) + 'Thousand '; n %= 1000; }
        if (n > 0) words += format(n);
        return words.trim() + ' Only';
      };

      // 1. HEADER & LOGO
      doc.setFillColor(15, 23, 42); // Deep Slate
      doc.rect(0, 0, 210, 45, 'F');
      
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(24);
      doc.setFont("helvetica", "bold");
      doc.text(businessName.toUpperCase(), 15, 25);
      
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(160, 170, 190);
      const headerAddr = doc.splitTextToSize(safeStr(business?.address), 100);
      doc.text(headerAddr, 15, 32);
      doc.text(`PH: ${safeStr(business?.phone)}  |  EM: ${safeStr(business?.email)}`, 15, 32 + (headerAddr.length * 4));

      // Right Side Header Info
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(18);
      doc.setFont("helvetica", "bold");
      doc.text("TAX INVOICE", 195, 20, { align: 'right' });
      
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.text(`NO: ${safeStr(invoice.invoice_number)}`, 195, 28, { align: 'right' });
      doc.text(`DATE: ${safeStr(invoice.invoice_date)}`, 195, 33, { align: 'right' });
      doc.setFont("helvetica", "bold");
      doc.setTextColor(159, 239, 0); // Neon Lime for GSTIN
      doc.text(`GSTIN: ${safeStr(business?.gstin)}`, 195, 38, { align: 'right' });

      // 2. BILLING
      currentY = 55;
      doc.setTextColor(15, 23, 42);
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.text("CUSTOMER DETAILS", 15, currentY);
      doc.setDrawColor(230, 230, 230);
      doc.line(15, currentY + 2, 70, currentY + 2);
      
      currentY += 8;
      doc.setFontSize(11);
      const contactName = safeStr(invoice.contacts?.name || "WALK-IN CUSTOMER");
      doc.text(contactName.toUpperCase(), 15, currentY);
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      const bAddr = doc.splitTextToSize(safeStr(invoice.contacts?.address), 80);
      doc.text(bAddr, 15, currentY + 5);
      
      const gstinY = currentY + 5 + (bAddr.length * 4) + 2;
      doc.setFont("helvetica", "bold");
      doc.text(`GSTIN: ${safeStr(invoice.contacts?.gstin)}`, 15, gstinY);

      // Status Stamp (Premium)
      if (invoice.status === 'paid') {
        doc.setDrawColor(16, 185, 129);
        doc.setLineWidth(1);
        doc.roundedRect(140, 55, 40, 15, 2, 2, 'S');
        doc.setTextColor(16, 185, 129);
        doc.setFontSize(14);
        doc.text("PAID", 160, 65, { align: 'center' });
      } else {
        doc.setDrawColor(244, 63, 94);
        doc.setLineWidth(1);
        doc.roundedRect(140, 55, 40, 15, 2, 2, 'S');
        doc.setTextColor(244, 63, 94);
        doc.setFontSize(14);
        doc.text("PENDING", 160, 65, { align: 'center' });
      }

      currentY = gstinY + 15;

      // 3. TABLE
      const tableBody = (items || []).map((it, idx) => {
        const qty = Number(it.quantity || 0);
        const price = Number(it.unit_price || 0);
        const taxRate = Number(it.tax_rate || 18);
        const taxable = qty * price;
        const taxAmount = taxable * (taxRate / 100);
        return [idx + 1, safeStr(it.product_name), safeStr(it.hsn_code), qty, price.toFixed(2), taxable.toFixed(2), (taxAmount / 2).toFixed(2), (taxAmount / 2).toFixed(2), "0.00", (taxable + taxAmount).toFixed(2)];
      });

      autoTable(doc, {
        startY: currentY,
        head: [['Sr.\nNo.', 'Description of Goods', 'HSN/SAC', 'Qty', 'Rate (Rs.)', 'Taxable\nValue (Rs.)', 'CGST\n(9%)', 'SGST\n(9%)', 'IGST\n(0%)', 'Total (Rs.)']],
        body: tableBody,
        theme: 'grid',
        styles: { fontSize: 7.5, cellPadding: 2, halign: 'center', textColor: [0, 0, 0], lineWidth: 0.1 },
        headStyles: { fillColor: [230, 230, 230], textColor: [0, 0, 0], fontStyle: 'bold' },
        columnStyles: { 0: { cellWidth: 10 }, 1: { halign: 'left' }, 3: { cellWidth: 10 } },
        margin: { left: 10, right: 10 }
      });

      const table = (doc as any).lastAutoTable;
      let finalY = table?.finalY || (currentY + 20);
      if (isNaN(finalY)) finalY = currentY + 20;

      const subtotal = items.reduce((acc, it) => acc + (Number(it.quantity || 0) * Number(it.unit_price || 0)), 0);
      const totalQty = items.reduce((acc, it) => acc + Number(it.quantity || 0), 0);
      const totalTax = items.reduce((acc, it) => acc + (Number(it.quantity || 0) * Number(it.unit_price || 0) * (Number(it.tax_rate || 18) / 100)), 0);
      const grandTotal = subtotal + totalTax;

      // Summary
      doc.setFillColor(245, 245, 245);
      doc.rect(10, finalY, 190, 8, 'F');
      doc.rect(10, finalY, 190, 8, 'S');
      doc.setFont("helvetica", "bold");
      doc.text(`Total Qty: ${totalQty}`, 15, finalY + 5.5);
      doc.text(`Subtotal: Rs. ${subtotal.toFixed(2)}`, 80, finalY + 5.5);
      doc.text(`Total Tax: Rs. ${totalTax.toFixed(2)}`, 130, finalY + 5.5);
      doc.text(`Total: Rs. ${grandTotal.toFixed(2)}`, 195, finalY + 5.5, { align: 'right' });

      finalY += 15;
      doc.setFontSize(9);
      doc.text(`Total Amount In Words: ${numberToWords(grandTotal)}`, 10, finalY);

      finalY += 10;
      doc.text("Bank Details:", 10, finalY);
      doc.setFont("helvetica", "normal");
      doc.text(`${safeStr(business?.bank_name)} | A/c: ${safeStr(business?.bank_account)} | IFSC: ${safeStr(business?.ifsc)}`, 10, finalY + 5);

      finalY += 20;
      doc.setFont("helvetica", "bold");
      doc.text("Declaration:", 10, finalY);
      doc.setFont("helvetica", "normal");
      doc.text("Certified that the particulars given above are true and correct.", 10, finalY + 5);

      const sigX = 175;
      doc.setFont("helvetica", "italic");
      doc.setFontSize(18);
      doc.text("U. Signatory", sigX, finalY + 10, { align: 'center' });
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.text(businessName.toUpperCase(), sigX, finalY + 16, { align: 'center' });

      const safeInvoiceNum = String(invoice.invoice_number || '').replace(/[^a-zA-Z0-9-]/g, '_');
      const filename = `Invoice_${safeInvoiceNum}.pdf`;
      
      downloadPDF(doc, filename);
    } catch (err) {
      console.error("[InvoicePDF] Error:", err);
    }
  },

  /**
   * High-fidelity Tally XML exporter generating structural ISO standard documents.
   */
  exportTallyXML: async (businessName: string, data: any[]) => {
    try {
      const { saveAs } = await import("file-saver");
      
      let voucherNodes = "";
      data.forEach((item, index) => {
        const isPurchase = item.is_purchase;
        const type = isPurchase ? "Purchase" : "Sales";
        const date = new Date(item.invoice_date || item.created_at).toISOString().split('T')[0].replace(/-/g, '');
        const amount = Number(item.total_amount || item.amount || 0).toFixed(2);
        const voucherNum = item.invoice_number || `VCH-${index + 1000}`;
        const partyName = item.contact_name || item.contact?.name || "Cash Account";

        voucherNodes += `
        <TALLYMESSAGE xmlns:UDF="TallyUDF">
          <VOUCHER VCHTYPE="${type}" ACTION="Create" OBJVIEW="Accounting Voucher View">
            <DATE>${date}</DATE>
            <VOUCHERTYPENAME>${type}</VOUCHERTYPENAME>
            <VOUCHERNUMBER>${voucherNum}</VOUCHERNUMBER>
            <PARTYLEDGERNAME>${partyName.replace(/&/g, '&amp;')}</PARTYLEDGERNAME>
            <ALLLEDGERENTRIES.LIST>
              <LEDGERNAME>${partyName.replace(/&/g, '&amp;')}</LEDGERNAME>
              <ISDEEMEDPOSITIVE>${isPurchase ? "No" : "Yes"}</ISDEEMEDPOSITIVE>
              <AMOUNT>${isPurchase ? amount : `-${amount}`}</AMOUNT>
            </ALLLEDGERENTRIES.LIST>
            <ALLLEDGERENTRIES.LIST>
              <LEDGERNAME>${isPurchase ? "Purchase Account" : "Sales Account"}</LEDGERNAME>
              <ISDEEMEDPOSITIVE>${isPurchase ? "Yes" : "No"}</ISDEEMEDPOSITIVE>
              <AMOUNT>${isPurchase ? `-${amount}` : amount}</AMOUNT>
            </ALLLEDGERENTRIES.LIST>
          </VOUCHER>
        </TALLYMESSAGE>`;
      });

      const finalXML = `<?xml version="1.0" encoding="utf-8"?>
<ENVELOPE>
  <HEADER>
    <TALLYREQUEST>Import Data</TALLYREQUEST>
  </HEADER>
  <BODY>
    <IMPORTDATA>
      <REQUESTDESC>
        <REPORTNAME>Vouchers</REPORTNAME>
        <STATICVARIABLES>
          <SVCURRENTCOMPANY>${businessName.replace(/&/g, '&amp;')}</SVCURRENTCOMPANY>
        </STATICVARIABLES>
      </REQUESTDESC>
      <REQUESTDATA>
        ${voucherNodes}
      </REQUESTDATA>
    </IMPORTDATA>
  </BODY>
</ENVELOPE>`;

      const blob = new Blob([finalXML], { type: "text/xml;charset=utf-8" });
      saveAs(blob, `Vyapari_TallyExport_${new Date().toISOString().split('T')[0]}.xml`);
      return true;
    } catch (error) {
      console.error("[TallyXML] Critical Failure:", error);
      throw error;
    }
  },

  /**
   * Generates a standard GSTR-1 JSON schema output for GST portal upload.
   * Maps B2B, B2C, HSN data.
   */
  exportGSTR1JSON: async (businessConfig: any, invoices: any[]) => {
    try {
      const { saveAs } = await import("file-saver");
      const currentMonth = new Date().getMonth() + 1;
      const currentYear = new Date().getFullYear();
      
      const payload: any = {
        "gstin": businessConfig?.gstin || "29XXXXX0000X0Z5",
        "fp": `${currentMonth.toString().padStart(2, '0')}${currentYear}`,
        "gt": 0,
        "cur_gt": 0,
        "b2b": [],
        "b2cs": [],
        "hsn": { "data": [] }
      };

      // Transform logic
      invoices.filter(i => !i.is_purchase).forEach(inv => {
        if (inv.contact?.gstin) {
          // B2B processing
          payload.b2b.push({
            "ctin": inv.contact.gstin,
            "inv": [{
              "inum": inv.invoice_number,
              "idt": inv.invoice_date.split('T')[0].split('-').reverse().join('-'), // DD-MM-YYYY
              "val": Number(inv.total_amount),
              "pos": inv.contact?.state_code || "29",
              "rchrg": "N",
              "inv_typ": "R",
              "itms": [] // simplified for demo
            }]
          });
        } else {
          // B2CS processing
          payload.b2cs.push({
            "sply_ty": "INTRA",
            "rt": 18, // dynamic rate logic goes here
            "txval": Number(inv.total_amount) * 0.82,
            "iamt": 0,
            "csamt": 0
          });
        }
      });

      const blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json;charset=utf-8" });
      saveAs(blob, `GSTR1_${payload.fp}_${payload.gstin}.json`);
      return true;
    } catch (error) {
      console.error("[GSTR1 Export] Failure:", error);
      throw error;
    }
  }
};
