import React from 'react';
import { motion } from 'motion/react';
import { X, MessageSquare, Edit3 } from 'lucide-react';
import { Theme } from '../PresentationMode';

interface PresenterNotesProps {
  slideIndex: number;
  onClose: () => void;
  theme: Theme;
}

export default function PresenterNotes({ slideIndex, onClose, theme }: PresenterNotesProps) {
  const notes = [
    "Welcome. This report was generated by Vyapari AI based on your actual sales data.",
    "AI analyzed your last 90 days of transactions to create this executive summary.",
    "These are conservative estimates. Actual results may be higher based on implementation quality.",
    "Each bar shows current vs projected revenue for that product. Note the growth potential.",
    "Green means the change is profitable. No red items - all products remain in the safety zone.",
    "The shaded area is our confidence band - 87% confidence based on historical variance.",
    "Break-even in 21 days means you see net profit from day 22. Highly achievable timeline.",
    "These are AI recommendations. You decide which to implement today or in the next week.",
    "Closing thought: Rs.1.5 lakhs per year additional revenue from just 2 price adjustments."
  ];

  const bgColor = theme === 'dark' ? 'bg-[#0F172A]/90' : 'bg-white/90';
  const textColor = theme === 'dark' ? 'text-white' : 'text-[#0F172A]';
  const borderColor = theme === 'dark' ? 'border-white/10' : 'border-slate-200';

  return (
    <motion.div
      initial={{ x: '100%' }}
      animate={{ x: 0 }}
      exit={{ x: '100%' }}
      className={`absolute top-0 right-0 bottom-0 w-80 ${bgColor} backdrop-blur-xl border-l ${borderColor} z-[60] p-8 flex flex-col`}
    >
      <div className="flex justify-between items-center mb-8">
        <div className="flex items-center gap-3">
          <MessageSquare size={18} className="text-indigo-500" />
          <h3 className={`text-[10px] font-black uppercase tracking-[0.3em] ${textColor}`}>Presenter Notes</h3>
        </div>
        <button onClick={onClose} className={`p-2 rounded-lg hover:bg-white/10 ${textColor}`}>
          <X size={18} />
        </button>
      </div>

      <div className="flex-1 overflow-y-auto pr-2 custom-scrollbar space-y-6">
        <div className="space-y-2">
          <div className="text-[8px] font-black text-slate-500 uppercase tracking-widest">Current Slide</div>
          <div className={`text-xs font-black ${textColor} uppercase`}>Slide {slideIndex + 1}</div>
        </div>

        <div className={`p-6 rounded-2xl bg-white/5 border ${borderColor} relative group`}>
          <div className="absolute top-4 right-4 opacity-20 group-hover:opacity-100 transition-opacity">
            <Edit3 size={14} className={textColor} />
          </div>
          <p className={`text-xs font-bold leading-relaxed italic ${textColor} opacity-80`}>
            "{notes[slideIndex] || "No specific notes for this slide."}"
          </p>
        </div>

        <div className="pt-8 border-t border-white/5 space-y-4">
          <div className="text-[8px] font-black text-slate-500 uppercase tracking-widest">Key Points</div>
          <ul className="space-y-3">
            {["Highlight growth", "Mention confidence", "Call to action"].map((point, i) => (
              <li key={i} className="flex items-center gap-3">
                <div className="w-1 h-1 rounded-full bg-indigo-500" />
                <span className={`text-[10px] font-bold ${textColor} opacity-60 uppercase tracking-wider`}>{point}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      <div className="mt-8 p-4 bg-indigo-600/10 rounded-xl border border-indigo-500/20">
        <p className="text-[9px] font-black text-indigo-400 uppercase leading-tight text-center">
          Pro Tip: Use arrow keys to navigate while reading notes.
        </p>
      </div>
    </motion.div>
  );
}
