import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface ExecutivePDFProps {
  businessName: string;
  reportTitle: string;
  period: string;
  gstin: string;
  kpis: { label: string; value: string; color?: string }[];
  chartImage?: string;
  aiAdvisory?: string[];
  tableData: any[];
  columns: string[];
  category?: string;
  description?: string;
}

const normalizeValue = (val: any) => {
  if (typeof val !== 'string') return val;
  return val.replace(/₹/g, 'INR');
};

export async function generateExecutivePDF({
  businessName, reportTitle, period, gstin, kpis, chartImage, aiAdvisory, tableData, columns, category, description
}: ExecutivePDFProps) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const INDIGO: [number, number, number] = [79, 70, 229];
  const SLATE_900: [number, number, number] = [15, 23, 42];
  const SLATE_50: [number, number, number] = [248, 250, 252];
  const NEON: [number, number, number] = [159, 239, 0];
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();

  const drawHeader = () => {
    // Official Logo / Branding Box
    doc.setFillColor(...SLATE_900);
    doc.roundedRect(15, 8, 18, 18, 2, 2, 'F');
    const initials = businessName.split(' ').map((x: string) => x[0]).join('').slice(0, 2).toUpperCase();
    doc.setFontSize(9); doc.setTextColor(255, 255, 255); doc.setFont('helvetica', 'bold');
    doc.text(initials, 24, 19, { align: 'center' });

    // Official Category & Company Header
    doc.setFontSize(8); doc.setTextColor(148, 163, 184); doc.setFont('helvetica', 'bold');
    doc.text(`${businessName.toUpperCase()}  ·  ${(category || 'GENERAL').toUpperCase()} REPORTS`, 38, 13);
    
    // Main Title
    doc.setFontSize(18); doc.setTextColor(...SLATE_900); doc.setFont('helvetica', 'bold');
    doc.text(reportTitle.toUpperCase(), 38, 20);

    // Official Status Label
    doc.text(`CONFIDENTIAL · OFFICIAL DOCUMENT`, w - 15, 13, { align: 'right' });
    doc.text(`HASH: VX-${(Math.random()*1000).toFixed(0)}`, w - 15, 18, { align: 'right' });

    doc.setDrawColor(...SLATE_900); doc.setLineWidth(1.5); doc.line(15, 30, w - 15, 30);
  };

  const drawFooter = (page: number, total: number) => {
    doc.setFontSize(7); doc.setTextColor(148, 163, 184); doc.setFont('helvetica', 'normal');
    doc.text(`Confidential — Generated by Vyapari | ${businessName}`, 15, h - 6);
    doc.text(`Page ${page} of ${total} | ${new Date().toLocaleString('en-IN')}`, w - 15, h - 6, { align: 'right' });
  };

  drawHeader();

  // Meta Information Block
  let nextY = 36;
  doc.setFillColor(...SLATE_50);
  doc.rect(15, nextY, w - 30, 10, 'F');
  doc.setFontSize(7); doc.setTextColor(100, 116, 139); doc.setFont('helvetica', 'bold');
  doc.text('PERIOD', 18, nextY + 4);
  doc.text('BRANCH / OUTLET', 65, nextY + 4);
  const metaHeaders = ['PERIOD', 'BRANCH / OUTLET', 'PREPARED BY', 'REPORT DATE'];
  const metaValues = [period.toUpperCase(), "MAIN_BRANCH", "OWNER / MANAGER", new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }).toUpperCase()];
  
  autoTable(doc, {
    startY: nextY,
    head: [metaHeaders],
    body: [metaValues.map(normalizeValue)],
    theme: 'grid',
    styles: { font: 'helvetica', fontSize: 7, cellPadding: 2 },
    headStyles: { fillColor: SLATE_50, textColor: [100, 116, 139], fontStyle: 'bold' }
  });
  
  nextY = (doc as any).lastAutoTable.finalY + 8;

  // KPI Highlights
  if (kpis.length > 0) {
    const n = Math.min(kpis.length, 4);
    const boxW = (w - 30 - (n - 1) * 4) / n;
    doc.setFontSize(8); doc.setTextColor(...SLATE_900); doc.setFont('helvetica', 'bold');
    doc.text('KEY HIGHLIGHTS', 15, nextY - 4);

    kpis.slice(0, 4).forEach((kpi, i) => {
      const x = 15 + i * (boxW + 4);
      doc.setFillColor(...SLATE_50); doc.setDrawColor(200, 210, 230); doc.setLineWidth(0.3);
      doc.roundedRect(x, nextY, boxW, 18, 2, 2, 'FD');
      doc.setFontSize(6.5); doc.setTextColor(100, 116, 139); doc.setFont('helvetica', 'normal');
      doc.text(kpi.label.toUpperCase(), x + boxW / 2, nextY + 6, { align: 'center' });
      doc.setFontSize(10); doc.setTextColor(...SLATE_900); doc.setFont('helvetica', 'bold');
      doc.text(normalizeValue(kpi.value), x + boxW / 2, nextY + 14, { align: 'center' });
    });
    nextY += 26;
  }
  if (chartImage) { doc.addImage(chartImage, 'PNG', 15, nextY, 180, 62); nextY += 67; }

  if (aiAdvisory && aiAdvisory.length > 0) {
    doc.setFontSize(8); doc.setTextColor(...SLATE_900); doc.setFont('helvetica', 'bold');
    doc.text('SUMMARY & INSIGHTS', 15, nextY);
    nextY += 4;
    
    const boxH = 10 + Math.min(aiAdvisory.length, 3) * 6;
    doc.setFillColor(...SLATE_50); doc.setDrawColor(230, 230, 230); doc.rect(15, nextY, 180, boxH, 'FD');
    doc.setFontSize(8); doc.setTextColor(30, 41, 59); doc.setFont('helvetica', 'normal');
    
    const combinedText = aiAdvisory.slice(0, 3).join(' ');
    const lines = doc.splitTextToSize(combinedText, 170);
    doc.text(lines, 20, nextY + 6);
    nextY += boxH + 8;
  }

  const displayCols = columns.slice(0, 6);
  const displayRows = tableData.slice(0, 10).map(row =>
    displayCols.map(col => {
      const val = row[col.toLowerCase().replace(/\s+/g, '_')] ?? row[col] ?? '';
      const formatted = typeof val === 'number' ? val.toLocaleString('en-IN') : String(val);
      return normalizeValue(formatted);
    })
  );

  autoTable(doc, {
    startY: nextY + 2,
    head: [displayCols.map(c => c.toUpperCase())],
    body: displayRows,
    styles: { font: 'helvetica', fontSize: 8, cellPadding: 3.5 },
    headStyles: { fillColor: SLATE_900, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 8 },
    alternateRowStyles: { fillColor: SLATE_50 },
    margin: { left: 15, right: 15 },
    didDrawPage: (data: any) => { if (data.pageNumber > 1) drawHeader(); drawFooter(data.pageNumber, (doc as any).internal.getNumberOfPages()); }
  });

  // Final Signatures Section
  const finalY = (doc as any).lastAutoTable.finalY + 15;
  if (finalY < h - 40) {
    doc.setDrawColor(200, 210, 230); doc.setLineWidth(0.2);
    doc.line(15, finalY + 15, 65, finalY + 15);
    doc.line(80, finalY + 15, 130, finalY + 15);
    doc.line(145, finalY + 15, 195, finalY + 15);
    
    doc.setFontSize(7); doc.setTextColor(...SLATE_900); doc.setFont('helvetica', 'bold');
    doc.text('PREPARED BY', 40, finalY + 20, { align: 'center' });
    doc.text('REVIEWED BY', 105, finalY + 20, { align: 'center' });
    doc.text('APPROVED BY', 170, finalY + 20, { align: 'center' });
    
    doc.setFontSize(6); doc.setTextColor(148, 163, 184); doc.setFont('helvetica', 'italic');
    doc.text('Name & Signature', 40, finalY + 24, { align: 'center' });
    doc.text('Name & Signature', 105, finalY + 24, { align: 'center' });
    doc.text('Name & Signature', 170, finalY + 24, { align: 'center' });
  }

  const totalPages = (doc as any).internal.pages.length - 1;
  doc.setPage(1); drawFooter(1, totalPages);

  // Proper Blob PDF download — fixes MIME type bug
  const pdfBuffer = doc.output('arraybuffer');
  const blob = new Blob([pdfBuffer], { type: 'application/pdf' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url; link.download = `${reportTitle.replace(/\s+/g, '_')}_Executive.pdf`;
  link.style.display = 'none';
  document.body.appendChild(link); link.click(); document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
