import jsPDF from 'jspdf';

interface SimplePDFProps {
  businessName: string;
  reportTitle: string;
  period: string;
  summaryPoints: string[];
  actionItems: string[];
  chartImage?: string;
}

export async function generateSimplePDF({
  businessName, reportTitle, period, summaryPoints, actionItems, chartImage
}: SimplePDFProps) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const INDIGO: [number, number, number] = [79, 70, 229];
  const SLATE_900: [number, number, number] = [15, 23, 42];
  const SLATE_50: [number, number, number] = [248, 250, 252];
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();

  const drawHeader = () => {
    doc.setFillColor(...SLATE_900);
    doc.roundedRect(15, 8, 18, 18, 2, 2, 'F');
    const initials = businessName.split(' ').map((x: string) => x[0]).join('').slice(0, 2).toUpperCase();
    doc.setFontSize(9); doc.setTextColor(255, 255, 255); doc.setFont('helvetica', 'bold');
    doc.text(initials, 24, 19, { align: 'center' });
    doc.setFontSize(15); doc.setTextColor(...SLATE_900); doc.text(businessName, 38, 15);
    doc.setFontSize(8); doc.setTextColor(100, 116, 139); doc.setFont('helvetica', 'normal');
    doc.text('Simplified Summary Report', 38, 21);
    doc.setFontSize(13); doc.setTextColor(...INDIGO); doc.setFont('helvetica', 'bold');
    doc.text(reportTitle, w - 15, 15, { align: 'right' });
    doc.setFontSize(8); doc.setTextColor(100, 116, 139); doc.setFont('helvetica', 'normal');
    doc.text(`Period: ${period}`, w - 15, 21, { align: 'right' });
    doc.setDrawColor(...INDIGO); doc.setLineWidth(0.6); doc.line(15, 30, w - 15, 30);
  };

  const drawFooter = () => {
    doc.setFontSize(7); doc.setTextColor(148, 163, 184); doc.setFont('helvetica', 'normal');
    doc.text(`Generated by Vyapari | ${businessName}`, 15, h - 6);
    doc.text(`Page 1 of 1 | ${new Date().toLocaleString('en-IN')}`, w - 15, h - 6, { align: 'right' });
  };

  drawHeader();

  // 1. What Happened Section
  doc.setFontSize(11); doc.setFont('helvetica', 'bold'); doc.setTextColor(...INDIGO);
  doc.text('WHAT HAPPENED THIS PERIOD?', 15, 42);

  doc.setFontSize(8.5); doc.setFont('helvetica', 'normal'); doc.setTextColor(...SLATE_900);
  let currentY = 50;
  summaryPoints.slice(0, 4).forEach(point => {
    doc.setFillColor(...INDIGO);
    doc.circle(18, currentY - 1, 0.7, 'F');
    doc.text(point, 22, currentY, { maxWidth: 170 });
    currentY += 8;
  });

  // 2. Visual Insight
  if (chartImage) {
    doc.addImage(chartImage, 'PNG', 15, currentY + 2, 180, 62);
    currentY += 70;
  }

  // 3. Next Steps Section
  doc.setFontSize(11); doc.setFont('helvetica', 'bold'); doc.setTextColor(...INDIGO);
  doc.text('WHAT TO DO NEXT?', 15, currentY + 4);

  doc.setFontSize(8.5); doc.setFont('helvetica', 'normal'); doc.setTextColor(...SLATE_900);
  currentY += 12;
  actionItems.slice(0, 4).forEach(item => {
    doc.setFillColor(...INDIGO);
    doc.circle(18, currentY - 1, 0.7, 'F');
    doc.text(item, 22, currentY, { maxWidth: 170 });
    currentY += 8;
  });

  drawFooter();

  // Safe Blob PDF download trigger
  const pdfBuffer = doc.output('arraybuffer');
  const blob = new Blob([pdfBuffer], { type: 'application/pdf' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url; link.download = `${reportTitle.replace(/\s+/g, '_')}_Summary.pdf`;
  link.style.display = 'none';
  document.body.appendChild(link); link.click(); document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
