import React from 'react';
import { motion } from 'motion/react';
import { Sparkles, ArrowUpRight, Zap } from 'lucide-react';
import CountUp from '../components/CountUpNumber';
import { Theme } from '../PresentationMode';

interface SlideProps {
  data: any;
  business: any;
  theme: Theme;
}

export default function ClosingSlide({ data, business, theme }: SlideProps) {
  const textColor = theme === 'dark' ? 'text-white' : 'text-[#0F172A]';
  const borderColor = theme === 'dark' ? 'border-white/10' : 'border-slate-200';
  const cardBg = theme === 'dark' ? 'bg-white/5' : 'bg-slate-50';

  const monthlyImpact = (data.simulated_scenario?.total_revenue_projected || 64800) - (data.current_scenario?.total_revenue || 52000);
  const yearlyImpact = monthlyImpact * 12;

  return (
    <div className="w-full h-full flex flex-col items-center justify-center relative overflow-hidden">
      {/* Background Particles/Glow */}
      <div className="absolute inset-0 z-0 overflow-hidden pointer-events-none">
        <div className="absolute top-1/4 left-1/4 w-64 h-64 bg-indigo-500/10 blur-[120px] rounded-full animate-pulse" />
        <div className="absolute bottom-1/4 right-1/4 w-64 h-64 bg-emerald-500/10 blur-[120px] rounded-full animate-pulse" style={{ animationDelay: '1s' }} />
      </div>

      <motion.div
        initial={{ opacity: 0, scale: 0.9 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 1 }}
        className="text-center z-10 space-y-12"
      >
        <div className="flex items-center justify-center gap-4">
          <Sparkles className="text-indigo-500" size={32} />
          <h2 className={`text-2xl font-black tracking-[0.5em] ${textColor} italic`}>VYAPARI INTELLIGENCE</h2>
        </div>

        <div className="space-y-4">
          <p className={`text-xl font-bold ${textColor} opacity-60 uppercase tracking-widest`}>Implementing these recommendations could increase your revenue by</p>
          
          <div className={`p-16 rounded-[4rem] border-2 border-indigo-500/30 ${cardBg} backdrop-blur-3xl shadow-2xl shadow-indigo-500/10 relative group`}>
            <div className="absolute top-0 right-0 p-10 text-indigo-500/5 group-hover:text-indigo-500/10 transition-colors">
              <Zap size={200} />
            </div>

            <div className="space-y-8 relative z-10">
              <div className="space-y-2">
                <div className={`text-8xl font-black ${textColor} tracking-tighter italic`}>
                  + <CountUp target={monthlyImpact} />
                </div>
                <div className="text-lg font-black text-indigo-400 uppercase tracking-[0.3em]">per month</div>
              </div>

              <div className="h-px bg-white/10 w-32 mx-auto" />

              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 1.5 }}
                className="space-y-2"
              >
                <div className={`text-5xl font-black text-emerald-500 tracking-tighter italic`}>
                  + <CountUp target={yearlyImpact} />
                </div>
                <div className="text-sm font-black text-emerald-500/60 uppercase tracking-[0.3em]">Estimated yearly gain</div>
              </motion.div>
            </div>
          </div>
        </div>

        <div className="flex flex-col items-center gap-4 pt-12">
          <div className={`text-[10px] font-black text-slate-500 uppercase tracking-[0.5em]`}>Report Generated by Vyapari AI</div>
          <div className={`text-[10px] font-black ${textColor} uppercase tracking-[0.2em]`}>{new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</div>
        </div>

        <motion.button
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
          className="mt-12 px-12 py-5 bg-white text-slate-900 rounded-[2rem] font-black uppercase tracking-[0.3em] text-xs shadow-2xl flex items-center gap-4 hover:bg-slate-100 transition-all"
        >
          Begin Implementation <ArrowUpRight size={20} />
        </motion.button>
      </motion.div>
    </div>
  );
}
