import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { saveAs } from 'file-saver';

//  CORE DOWNLOAD FUNCTION 
// Use this for every single PDF download
export const downloadPDF = (
  doc: jsPDF,
  filename: string
): void => {
  // 1. Enforce strict Vyapari Naming Rule: vyapari-[report-type]-[YYYY-MM-DD].pdf
  const dateStr = new Date().toISOString().slice(0, 10);
  let baseName = filename.trim().toLowerCase().replace(/\.pdf$/i, '').replace(/[^a-z0-9]+/g, '-');
  
  // Ensure prefix is there
  if (!baseName.startsWith('vyapari')) {
    baseName = `vyapari-${baseName}`;
  }

  // Ensure date is appended if not present already
  const cleanName = `${baseName}-${dateStr}`.replace(/--+/g, '-') + '.pdf';

  try {
    // 2. Generate explicit ArrayBuffer and pack into forced-type Blob
    const pdfBytes = doc.output('arraybuffer');
    const blob = new Blob([pdfBytes], { type: 'application/pdf' });
    
    // 3. Dispatch via industry-standard hardened downloader
    // saveAs provides exhaustive fallback matrices for all browsers to prevent UUID renames.
    saveAs(blob, cleanName);

  } catch (error) {
    console.error('[PDF] Optimized transport failed, attempting native save:', error);
    try {
      // Last ditch fallback provided by jsPDF native engine
      doc.save(cleanName);
    } catch (fallbackError) {
      console.error('[PDF] Critical failure downloading PDF:', fallbackError);
      alert('Could not initiate download automatically. Please try viewing and saving manually.');
    }
  }
};

export const openPDFInTab = (
  doc: jsPDF
): void => {
  try {
    const pdfBytes = doc.output('arraybuffer');
    const blob = new Blob([pdfBytes], { type: 'application/pdf' });
    const url = URL.createObjectURL(blob);
    window.open(url, '_blank');
    // Cleanup later to ensure browser can load it
    setTimeout(() => URL.revokeObjectURL(url), 3000);
  } catch (error) {
    console.error('[PDF] Failed to open in tab:', error);
    // Safe data-uri fallback
    try {
      const dataUri = doc.output('datauristring');
      const win = window.open();
      if (win) {
        win.document.write('<iframe src="' + dataUri + '" frameborder="0" style="border:0; top:0px; left:0px; bottom:0px; right:0px; width:100%; height:100%;" allowfullscreen></iframe>');
      }
    } catch (e) {
      console.error('[PDF] Final open fallback failed:', e);
    }
  }
};

//  VYAPARI PDF BRAND HEADER 
export const addVyapariHeader = (
  doc: jsPDF,
  title: string,
  businessName: string,
  subtitle?: string
): number => {
  const pageWidth = doc.internal.pageSize.width;

  // Brand header background
  doc.setFillColor(79, 70, 229); // --color-brand
  doc.rect(0, 0, pageWidth, 28, "F");

  // Vyapari logo text
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("VYAPARI", 14, 11);

  // Neon accent line
  doc.setDrawColor(159, 239, 0); // --color-neon
  doc.setLineWidth(0.8);
  doc.line(14, 14, 55, 14);

  // Business name right side
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(businessName, pageWidth - 14, 11, {
    align: "right",
  });

  // Date right side
  doc.text(
    new Date().toLocaleDateString("en-IN", {
      day: "2-digit",
      month: "short",
      year: "numeric",
    }),
    pageWidth - 14,
    17,
    { align: "right" }
  );

  // Report title
  doc.setTextColor(79, 70, 229);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(title, 14, 42);

  // Subtitle
  if (subtitle) {
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.setFont("helvetica", "normal");
    doc.text(subtitle, 14, 50);
    return 58;
  }

  return 50;
};

//  VYAPARI PDF FOOTER 
export const addVyapariFooter = (
  doc: jsPDF
): void => {
  const pageCount = doc.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);

    // Footer line
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.3);
    doc.line(14, pageHeight - 14, 
             pageWidth - 14, pageHeight - 14);

    // Footer text
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.setFont("helvetica", "normal");
    doc.text(
      `Page ${i} of ${pageCount}`,
      14,
      pageHeight - 8
    );
    doc.text(
      "Generated by Vyapari Intelligence Platform",
      pageWidth / 2,
      pageHeight - 8,
      { align: "center" }
    );
    doc.text(
      "Confidential",
      pageWidth - 14,
      pageHeight - 8,
      { align: "right" }
    );
  }
};

//  STANDARD TABLE STYLES 
export const tableStyles = {
  headStyles: {
    fillColor: [79, 70, 229] as [number, number, number],
    textColor: [255, 255, 255] as [number, number, number],
    fontStyle: "bold" as const,
    fontSize: 9,
  },
  alternateRowStyles: {
    fillColor: [248, 250, 252] as [number, number, number],
  },
  styles: {
    fontSize: 9,
    cellPadding: 3,
  },
  margin: { left: 14, right: 14 },
};
