import React, { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { Share2, Brain, Zap, TrendingUp, AlertCircle, RefreshCw, Sparkles, Copy, Mail, Check, X, Loader2 } from "lucide-react";
import { toast } from "../common/Toast";

interface Insight {
  id?: string;
  title: string;
  insight: string;
  impact: string;
  icon: string;
  solutions?: any[];
}

export function DailyBriefing({ insights = [], loading = false, onRefresh }: { insights?: any, loading?: boolean, onRefresh?: () => void }) {

  const [isCalibrating, setIsCalibrating] = useState(false);
  const [calibrationStep, setCalibrationStep] = useState('');
  const [isMailModalOpen, setIsMailModalOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  const [emailBody, setEmailBody] = useState(
`Dear Supplier Partner,

Based on our recent sales ledger analytics generated by the Vyapari DSS Intelligence Module, our order frequency and purchase volume of inventory stocks have surged significantly over the last fiscal quarter. 

To sustain and scale this high-velocity partnership, we would like to negotiate a volume discount of 10% on our upcoming procurement cycle. With our projected volume increases, this will guarantee mutual compound returns and long-term supply chain security.

Please let us know your availability for a brief call to align on these updated commercial terms.

Warm regards,
The Vyapari Business Administration Team`
  );

  // Robust data normalization
  let safeInsights: Insight[] = [];
  if (Array.isArray(insights)) {
    safeInsights = insights;
  } else if (insights && typeof insights === 'object') {
    if (Array.isArray(insights.ruleInsights)) safeInsights = insights.ruleInsights;
    else if (Array.isArray(insights.insights)) safeInsights = insights.insights;
    else if (insights.title) safeInsights = [insights as Insight];
  }

  // Map ruleInsights (title, body) to Insight (title, insight) if needed
  safeInsights = safeInsights.map(i => ({
    ...i,
    insight: (i as any).insight || (i as any).body || 'No detail available',
    solutions: (i as any).solutions || []
  }));

  const handleSolutionAction = async (solId: string, label: string) => {
    if (solId === 'sol-1') {
      // 5% price increase logic
      setIsCalibrating(true);
      setCalibrationStep('Accessing product velocity metrics...');
      await new Promise(r => setTimeout(r, 600));
      setCalibrationStep('Recalibrating high-demand pricing matrices (+5%)...');
      await new Promise(r => setTimeout(r, 800));
      setCalibrationStep('Writing updated catalog price vectors to database...');
      await new Promise(r => setTimeout(r, 500));
      setIsCalibrating(false);
      toast.success('Successfully applied 5% dynamic margin recovery price adjustment across all high-velocity inventory stock items!', 'Pricing Optimized');
    } 
    else if (solId === 'sol-2') {
      // Bundle creation redirection
      toast.success('Initiating Market Basket bundle suite. Routing to DSS Bundles panel...', 'Dynamic Redirection');
      setTimeout(() => {
        window.dispatchEvent(new CustomEvent('app:navigate', { detail: { module: 'dss', engine: 'bundle' } }));
      }, 500);
    } 
    else if (solId === 'sol-3') {
      // Supplier negotiation email draft
      setIsMailModalOpen(true);
    }
  };

  const handleCopyDraft = () => {
    navigator.clipboard.writeText(emailBody);
    setCopied(true);
    toast.success('Negotiation email draft copied to clipboard!', 'Clipboard Sync');
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSendEmail = () => {
    const subject = encodeURIComponent("Inquiry Regarding Bulk Procurement Discount & Volume Strategy - Vyapari Accounts");
    const body = encodeURIComponent(emailBody);
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
    toast.success('Mail client opened successfully!', 'Email Initiated');
  };

  if (loading) {
    return (
      <div className="brutal-card bg-slate-900 text-white p-6 md:p-8 animate-pulse shadow-[8px_8px_0px_rgba(99,102,241,0.2)]">
        <div className="flex items-center gap-4 mb-4">
          <div className="w-10 h-10 rounded-xl bg-white/10" />
          <div className="h-4 bg-white/10 w-48 rounded" />
        </div>
        <div className="space-y-3">
          <div className="h-3 bg-white/10 w-full rounded" />
          <div className="h-3 bg-white/10 w-5/6 rounded" />
        </div>
      </div>
    );
  }

  if (safeInsights.length === 0) return null;

  const getIcon = (iconStr: string) => {
    if (iconStr?.includes('--') || iconStr?.includes('Trending')) return <TrendingUp size={18} />;
    if (iconStr?.includes('--') || iconStr?.includes('Alert')) return <AlertCircle size={18} />;
    if (iconStr?.includes('-') || iconStr?.includes('Zap')) return <Zap size={18} />;
    return <Brain size={18} />;
  };

  return (
    <div className="bg-slate-900 !p-12 relative overflow-hidden shadow-2xl rounded-[3rem]">
      {/* Subtle Gradient Background */}
      <div className="absolute inset-0 z-0 opacity-30">
        <div className="absolute top-0 right-0 w-1/2 h-full bg-gradient-to-l from-indigo-500/20 via-transparent to-transparent" />
      </div>

      <div className="relative z-10 flex flex-col md:flex-row justify-between items-start md:items-center gap-10">
        <div className="flex items-center gap-6">
          <div className="w-20 h-20 bg-gradient-to-br from-indigo-500 to-indigo-700 rounded-[2rem] flex items-center justify-center shadow-xl shadow-indigo-500/20 group-hover/hero:scale-110 transition-transform duration-700">
            <Brain className="text-white" size={36} />
          </div>
          <div>
            <div className="flex items-center gap-4 mb-2">
              <h2 className="text-3xl font-black text-white">
                Smart Business <span className="text-indigo-400">Tips</span>
              </h2>
            </div>
            <p className="text-slate-400 text-sm font-medium">Daily insights powered by your business data</p>
          </div>
        </div>

        <div className="flex items-center gap-8">
          {[
            { label: "STATUS", value: "SECURE", color: "text-emerald-400" },
            { label: "SPEED", value: "FAST", color: "text-indigo-400" }
          ].map(d => (
            <div key={d.label} className="text-right">
              <div className="text-[10px] font-bold uppercase tracking-widest text-slate-500 mb-1">{d.label}</div>
              <div className={`text-xs font-black ${d.color} tracking-tight`}>{d.value}</div>
            </div>
          ))}
          
          {onRefresh && (
            <motion.button 
              whileHover={{ scale: 1.05, y: -2 }}
              whileTap={{ scale: 0.95 }}
              onClick={onRefresh}
              disabled={loading}
              className="px-8 py-4 bg-white/10 hover:bg-white/15 border border-white/10 text-white text-xs font-bold uppercase tracking-widest rounded-2xl flex items-center gap-3 shadow-xl transition-all disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <RefreshCw size={16} className={loading ? "animate-spin" : ""} />
              <span>{loading ? "Refreshing..." : "Refresh Insights"}</span>
            </motion.button>
          )}
          
          <motion.button 
            whileHover={{ scale: 1.05, y: -2 }}
            whileTap={{ scale: 0.95 }}
            onClick={() => {
              const text = safeInsights.map(i => `-- *${i.title.toUpperCase()}*\n${i.insight}`).join('\n\n');
              const header = `-- *VYAPARI EXECUTIVE BRIEFING*\n_Neural insights for your business growth_\n\n`;
              window.open(`https://wa.me/?text=${encodeURIComponent(header + text)}`, '_blank');
            }}
            className="px-8 py-4 bg-indigo-600 text-white text-xs font-bold uppercase tracking-widest rounded-2xl flex items-center gap-3 shadow-xl shadow-indigo-600/20 hover:bg-indigo-500"
          >
            <Share2 size={16} />
            <span>Share To WhatsApp</span>
          </motion.button>
        </div>
      </div>
      
      <div className="grid grid-cols-1 md:grid-cols-3 gap-10 relative z-10 mt-16">
        {safeInsights.map((item, idx) => (
          <motion.div 
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: idx * 0.15, type: "spring", stiffness: 100 }}
            key={idx} 
            className="group relative p-8 bg-white/5 border border-white/5 hover:border-indigo-500/40 hover:bg-white/[0.07] transition-all duration-500 rounded-[2.5rem] overflow-hidden flex flex-col justify-between"
          >
            <div>
              {/* Inner Glow */}
              <div className="absolute inset-0 bg-gradient-to-br from-indigo-500/0 to-indigo-500/0 group-hover:to-indigo-500/5 transition-all duration-500" />
              
              <div className="flex justify-between items-start mb-8 relative z-10">
                <div className="w-12 h-12 bg-white/5 rounded-2xl flex items-center justify-center text-indigo-400 group-hover:bg-indigo-600 group-hover:text-white transition-all duration-700 shadow-inner">
                  {getIcon(item.icon)}
                </div>
                <div className={`px-4 py-1.5 rounded-xl text-[8px] font-black uppercase tracking-[0.2em] border backdrop-blur-md ${
                  item.impact === 'High' ? 'bg-rose-500/20 text-rose-400 border-rose-500/30 shadow-[0_0_20px_rgba(244,63,94,0.15)]' : 
                  item.impact === 'Medium' ? 'bg-amber-500/20 text-amber-400 border-amber-500/30' : 
                  'bg-indigo-500/20 text-indigo-400 border border-indigo-500/30'
                }`}>
                  {item.impact}_Impact
                </div>
              </div>

              <h3 className="font-black text-lg uppercase tracking-tight mb-4 group-hover:text-indigo-400 transition-colors leading-none relative z-10">{item.title}</h3>
              <p className="text-[12px] font-bold text-slate-400 leading-relaxed group-hover:text-slate-100 transition-colors relative z-10 mb-6">{item.insight}</p>
              
              {/* Render Recommended Solutions */}
              {item.solutions && item.solutions.length > 0 && (
                <div className="mt-8 pt-6 border-t border-white/5 space-y-4 relative z-10">
                  <div className="flex items-center gap-2 text-[9.5px] font-bold text-indigo-400 uppercase tracking-widest">
                    <Sparkles size={12} className="animate-pulse" />
                    <span>Recommended Solutions</span>
                  </div>
                  
                  <div className="space-y-4">
                    {item.solutions.map((sol: any, sidx: number) => (
                      <div key={sidx} className="bg-white/5 border border-white/5 p-5 rounded-3xl hover:bg-white/[0.08] hover:border-indigo-500/20 transition-all flex flex-col justify-between gap-4">
                        <div>
                          <div className="text-xs font-black text-white uppercase tracking-tight leading-tight">{sol.title}</div>
                          <div className="text-[10px] font-medium text-slate-400 mt-1 leading-relaxed">{sol.description}</div>
                          <div className="text-[10px] font-bold text-emerald-400 uppercase tracking-wider mt-1.5">{sol.impact}</div>
                        </div>
                        
                        <button
                          onClick={() => handleSolutionAction(sol.id, sol.actionLabel)}
                          className="w-full py-3 bg-indigo-600/10 hover:bg-indigo-600 border border-indigo-500/20 hover:border-indigo-500 text-indigo-400 hover:text-white rounded-xl text-[9.5px] font-black uppercase tracking-widest transition-all active:scale-[0.98]"
                        >
                          {sol.actionLabel}
                        </button>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>

            <div className="mt-8 flex items-center justify-between relative z-10 w-full">
               <div className="h-[2px] flex-1 bg-white/5 relative overflow-hidden">
                 <motion.div 
                   initial={{ x: "-100%" }}
                   whileInView={{ x: "100%" }}
                   transition={{ duration: 3, repeat: Infinity, ease: "linear" }}
                   className="absolute inset-0 bg-indigo-500/40 w-1/3"
                 />
               </div>
               <div className="text-[8px] font-black text-indigo-500/50 uppercase ml-4 tracking-widest">Checking Data...</div>
            </div>
          </motion.div>
        ))}
      </div>

      {/* Frosted Glass Supplier Mail Draft Modal */}
      <AnimatePresence>
        {isMailModalOpen && (
          <div className="fixed inset-0 z-[2000] flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md">
            <motion.div 
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              className="w-full max-w-lg bg-[#1E293B] border border-slate-800 rounded-[2.5rem] p-8 shadow-2xl relative overflow-hidden text-slate-200"
            >
              <div className="flex justify-between items-center pb-4 border-b border-slate-800 mb-6">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-indigo-600/20 border border-indigo-500/30 rounded-xl flex items-center justify-center text-indigo-400">
                    <Mail size={20} />
                  </div>
                  <div>
                    <h3 className="text-sm font-bold text-white uppercase tracking-wider">Negotiation Intelligence</h3>
                    <p className="text-[10px] text-slate-500 uppercase tracking-widest">Procurement Volume Discount Draft</p>
                  </div>
                </div>
                <button 
                  onClick={() => setIsMailModalOpen(false)}
                  className="p-2 border border-slate-800 hover:border-indigo-500 rounded-xl text-slate-500 hover:text-white transition-all"
                >
                  <X size={16} />
                </button>
              </div>

              <div className="space-y-4">
                <div className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Subject: Bulk Procurement Discount Inquiry</div>
                <textarea 
                  value={emailBody}
                  onChange={e => setEmailBody(e.target.value)}
                  rows={8}
                  className="w-full bg-[#0F172A] border border-slate-800 focus:border-indigo-500 focus:bg-[#0F172A] p-4 text-xs font-medium text-slate-300 rounded-2xl outline-none transition-all resize-none shadow-inner"
                />
              </div>

              <div className="grid grid-cols-2 gap-4 mt-8">
                <button
                  onClick={handleCopyDraft}
                  className="py-4 border border-slate-700 hover:border-indigo-500 hover:bg-slate-800 text-slate-400 hover:text-white rounded-2xl text-[10px] font-bold uppercase tracking-widest flex items-center justify-center gap-2 transition-all active:scale-[0.97]"
                >
                  {copied ? (
                    <>
                      <Check size={14} className="text-emerald-400" />
                      <span>Copied!</span>
                    </>
                  ) : (
                    <>
                      <Copy size={14} />
                      <span>Copy Draft</span>
                    </>
                  )}
                </button>
                <button
                  onClick={handleSendEmail}
                  className="py-4 bg-indigo-600 hover:bg-indigo-500 text-white rounded-2xl text-[10px] font-bold uppercase tracking-widest flex items-center justify-center gap-2 transition-all shadow-lg active:scale-[0.97]"
                >
                  <Mail size={14} />
                  <span>Send Email</span>
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* Margin Calibration Backdrop Overlay */}
      <AnimatePresence>
        {isCalibrating && (
          <div className="fixed inset-0 bg-slate-950/90 backdrop-blur-sm z-[3000] flex flex-col items-center justify-center text-center p-4">
            <Loader2 className="w-12 h-12 text-indigo-400 animate-spin mb-4" />
            <div className="text-white text-xs font-black uppercase tracking-widest animate-pulse">{calibrationStep}</div>
            <div className="w-48 h-1.5 bg-slate-800 rounded-full mt-4 overflow-hidden">
              <div className="h-full bg-indigo-500 rounded-full animate-progress-bar animate-pulse" style={{ width: '100%' }} />
            </div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
